### ISSUE TITLE
Neha Daily Priorities

### ISSUE THREAD

**Issue by imraan-ecsion** [imraan-ecsion/DailyPriorities#2]
**Tasks for 04-22-2019**
1. Find the issue with AutoRefresh connections on query manager page and make appropriate changes along testing with Saurabh. [1 hour]
2. Complete the encryption/decryption logic with testing. [1.5 hours]

**Comment by NehaB12** [comment]
Tasks for 04-22-2019 -
1.Task With AutoRefresh Connection compled by removing async and await method.

**Comment by NehaB12** [comment]
04-22-2019 --Task Comment

1.Testing of AutoRefresh Functionality -->with Saurabh Gateway is Done and its working Properly.
2.Task 2 is not completed because Saurabha have to change their code as per Deepak sir.
3.Gateway Checkins Functionality -->Working
